baseURL = "https://neohsu.github.io/"
languageCode = "zh-tw"
DefaultContentLanguage = "zh-tw"
theme = "anatole"
summarylength = 5
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
profilePicture = "http://www.gravatar.com/avatar/a6974d6335aac6400019a5bd307aeca8?s=500"
title = "Learn Or Die"
author = "Neo Hsu"
description = "Code wins arguments."