baseURL = "https://neohsu.github.io/"
languageCode = "en-us"
title = "Learn Or Die"
theme = "hyde"

[Menus]
  main = [
      {Name = "GitHub", URL = "https://github.com/neohsu"}
  ]

[params]
  themeColor = "theme-base-09"
  description = "Code wins arguments."