baseURL = "https://neohsu.github.io/"
languageCode = "en-us"
title = "Learn Or Die"
theme = "hyde"

[Menus]
  main = [
      {Name = "GitHub", URL = "https://github.com/neohsu"}
  ]

[params]
  themeColor = "theme-base-09"
  description = "Code wins arguments."
  avatarURL = "http://www.gravatar.com/avatar/a6974d6335aac6400019a5bd307aeca8?s=200"